package rules.filterRules

import com.ftn.model.specification.FilterSpecification
import com.ftn.model.track.TrackCandidate
import com.ftn.model.track.Track
import com.ftn.util.Scoring

rule "Filter explicit songs"
    when
        $fs: FilterSpecification( allowExplicit == false )
        $c: TrackCandidate( $trackId: trackId )
        $t: Track( id == $trackId )
        eval( $t.getExplicit() )  
    then
        delete($c);
end

rule "Filter genre difference"
    when
        $fs : FilterSpecification( contextGenreIds != null, contextGenreMaxDifference != null )
        $c  : TrackCandidate( $trackId : trackId )
        $t  : Track( id == $trackId )
        eval( Scoring.distance($t.getGenreIds(), $fs.getContextGenreIds()) >= $fs.getContextGenreMaxDifference() )
    then
        delete($c);
end

rule "Filter forbidden tracks"
    when
        $fs : FilterSpecification( forbiddenTrackIds != null )
        $c  : TrackCandidate( $trackId : trackId )
        eval( $fs.getForbiddenTrackIds().contains($trackId) )
    then
        delete($c);
end
