package rules.filterRules

import com.ftn.model.specification.FilterSpecification
import com.ftn.model.track.TrackCandidate
import com.ftn.model.track.Track
import com.ftn.util.Scoring

rule "Filter explicit songs"
    when
        $fs: FilterSpecification( allowExplicit == false )
        $c: TrackCandidate( $trackId: trackId )
        $t: Track( id == $trackId )
        eval( $t.getExplicit() )  
    then
        delete($c);
end

rule "Filter genre difference"
    when
        $fs : FilterSpecification( contextGenres != null, genreDistanceMax != null )
        $c  : TrackCandidate( $trackId : trackId )
        $t  : Track( id == $trackId )
        eval( Scoring.distance($t.getGenres(), $fs.getContextGenreIds()) > $fs.getGenreDistanceMax() )
    then
        delete($c);
end